apiVersion: v2
actions:
  - name: "Run Checkov Container"
    events:
      - name: "sh.keptn.event.securityscan.triggered"
    tasks:
      - name: "Scan Files with Checkov"
        image: "bridgecrew/checkov:2.0.765"
        files:
          - job/checkov/plan1.json
        args:
          - '-f'
          - /keptn/job/checkov/plan2.json
          - '--framework'
          - "terraform"
          - '-o'
          - 'json'
